# Config from github
---
- hosts: localhost
  connection: local

  vars:
    repo_url: https://github.com/matthieup/config
    config_dir: /tmp/configansible


  tasks:
    - name: install my packages
      package:
         name:
           - vim
           - powerline
         state: latest

    - name: get config repository from github
      git: 
        repo: "{{ repo_url }}"
        dest: "{{ config_dir }}"
        version: master

    - name: copy ssh key from yubikey
      authorized_key:
        user: "{{ user }}" 
        state: present
        key: "{{ lookup('file', '/tmp/configansible/yubikey-ssh-pub') }}"

    - name: copy vimrc
      copy:
        src: "{{ config_dir }}/.vimrc"
        dest: "/home/{{ user }}/.vimrc"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0660

    - name: get vundle
      git:
        repo: "https://github.com/VundleVim/Vundle.vim.git"
        dest: "/home/{{ user }}/.vim/bundle/Vundle.vim"
        version: master

    - name: chown vim
      command: "chown -R {{ user }} /home/{{ user }}/.vim"
      args:
        warn: no

    - name: get plugins
      command: vim +PluginInstall +qall
      become: yes
      become_user: "{{ user }}"
      args:
        stdin: "\n"

  post_tasks:
    - name: Remove config files
      file: path="{{ config_dir }}" state=absent
